In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import pandas as pd

df = pd.read_csv('./PlayTennis.csv')
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [17]:
df = df.replace('Sunny', 0)
df = df.replace('Rain', 1)
df = df.replace('Overcast', 2)

df = df.replace('Hot', 0)
df = df.replace('Mild', 1)
df = df.replace('Cool', 2)

df = df.replace('Normal', 0)
df = df.replace('High', 1)

df = df.replace('Weak', 0)
df = df.replace('Strong', 1)

df = df.replace('Yes', 0)
df = df.replace('No', 1)

df

C:\Users\Prath\AppData\Local\Temp\ipykernel_13736\320267873.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('No', 1)

    Outlook  Temperature  Humidity  Wind  Play Tennis
0         0            0         1     0            1
1         0            0         1     1            1
2         2            0         1     0            0
3         1            1         1     0            0
4         1            2         0     0            0
5         1            2         0     1            1
6         2            2         0     1            0
7         0            1         1     0            1
8         0            2         0     0            0
9         1            1         0     0            0
10        0            1         0     1            0
11        2            1         1     1            0
12        2            0         0     0            0
13        1            1         1     1            1

In [19]:
x = df.drop(columns='Play Tennis').values
x

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [2, 0, 1, 0],
       [1, 1, 1, 0],
       [1, 2, 0, 0],
       [1, 2, 0, 1],
       [2, 2, 0, 1],
       [0, 1, 1, 0],
       [0, 2, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 1],
       [2, 1, 1, 1],
       [2, 0, 0, 0],
       [1, 1, 1, 1]], dtype=int64)

In [21]:
y = df['Play Tennis'].values
y

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

model = GaussianNB()
model.fit(x_train, y_train)
yp = model.predict(x_test)
yp

array([1, 0, 1, 1], dtype=int64)

In [27]:
y_test

array([0, 0, 0, 1], dtype=int64)